#jdbcConnection configuration
driverClassName=com.mysql.cj.jdbc.Driver
API_KEY=sk-8fd4c5c7d9cb4ea28c92d1885cb49644
MODEL=qwen-turbo
username=root
password=123456
url=jdbc:mysql://localhost:3306/yt_music?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
#mailConnection configuration
fromEmail=3588172935@qq.com
EmailPassword=fafbvzbmdazqcihj
Whitelist=login,register,static,EmailServlet


