#jdbcConnection configuration
driverClassName=com.mysql.cj.jdbc.Driver
API_KEY=ai接口
MODEL=特定版本的大语言模型
username=你的名字
password=你的密码
url=jdbc:mysql://主机ip:3306/数据库名?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
#mailConnection configuration
fromEmail=你的邮箱@qq.com
EmailPassword=你的邮箱授权码
Whitelist=login,register,static,EmailServlet


